[build]
  command = "npx eleventy"
  publish = "_site"
  functions = "netlify/functions"

[dev]
  command = "npx eleventy --serve"
  targetPort = 8080
  port = 8888
  functions = "netlify/functions"


